title: ElfTech Adventures: The FrostByte Flyer Challenge
description: Join the elite team of ElfTech engineers on a thrilling quest to repair the FrostByte Flyer! Dive into a world where electronics, coding, and Christmas magic collide. Perfect for tech enthusiasts and puzzle solvers of all ages, this interactive escape room adventure challenges you to use your skills to save Christmas. Are you ready to light up the holidays with your Arduino expertise?
theme: just-the-docs

url: https://just-the-docs.github.io

logo: "../assets/images/logo_256.png"

favicon_ico: "../assets/images/favicon.ico"

color_scheme: dark

search_enabled: false

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
